theme: jekyll-theme-modernist
title: String type = "Hello, World!";
description: A writer and community developer seeking to create spaces where information and knowledge can travel openly. Admittedly new to programming, but excited for the learning journey, and thrilled to have y'all along for the ride!
  
  Rock n Roll!
