theme: jekyll-theme-modernist
title: |
Drink to Me, Drink to my Health or Bars and Cultural 
Emergence Within Third Places
description: What roles do local bars play in the contexts of urban university communities?
